dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
    - SETTINGS=testing
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database task23jul2019_test;' -U postgres
script:
  - py.test -v -q --flakes --cov-config=.coveragerc --cov=app --cov-report=term-missing --doctest-modules tests
after_success:
  - coveralls
